import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import { Archive, ArrowUp, CalendarDays, ChevronLeft, ChevronRight, CirclePlus, Eye, Pencil, Plus, RotateCcw, Search, Trash2 } from 'lucide-react'
import { EmptyState, Modal, Pagination, PageLayout } from '../components/ui'
import { getApiErrorMessage } from '../api/client'
import { pmsService } from '../services/pmsService'
import { DashboardDeadlines, DashboardTable, DonutChart, MetricCards, PageControls, PageFooter, Panel, ProgressBar, GoalStatus, TrendChart, defaultRange, localDate } from './PmsUI'

const tabs = [{ id: 'overview', label: 'Overview' }, { id: 'team', label: 'Team Goals' }, { id: 'my', label: 'My Goals' }, { id: 'department', label: 'Department Goals' }, { id: 'alignment', label: 'Goal Alignment' }, { id: 'calendar', label: 'Goal Calendar' }, { id: 'archived', label: 'Archived Goals' }]
const scopes = { team: 'TEAM', my: 'MY', department: 'ALL', archived: 'ARCHIVED' }
const emptyForm = { title: '', description: '', employeeId: '', departmentId: '', categoryId: '', goalType: 'INDIVIDUAL', kraId: '', kpiId: '', weightage: 10, targetValue: 100, unit: '%', progressPercent: 0, priority: 'MEDIUM', alignmentGoalId: '', managerId: '', status: 'NOT_STARTED', startDate: localDate(new Date()), dueDate: localDate(new Date(Date.now() + 30 * 86400000)) }
const dateLabel = (value) => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${value.slice(0, 10)}T00:00:00`)) : '—'

function GoalModal({ goal, onClose, onSaved, notify }) {
  const [options, setOptions] = useState({ categories: [], kras: [], kpis: [], departments: [] }); const [employees, setEmployees] = useState([])
  const [search, setSearch] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const initial = goal ? { ...emptyForm, ...goal, employeeId: goal.employeeId || '', departmentId: goal.departmentId || '', categoryId: goal.categoryId || '', kraId: goal.kraId || '', kpiId: goal.kpiId || '', alignmentGoalId: goal.alignmentGoalId || '', managerId: goal.managerId || '' } : emptyForm
  const { register, handleSubmit, watch, setValue, formState: { errors } } = useForm({ defaultValues: initial })
  const categoryId = watch('categoryId'); const kraId = watch('kraId'); const status = watch('status')
  useEffect(() => { const c = new AbortController(); Promise.all([pmsService.lookups(c.signal), pmsService.departments(c.signal)]).then(([lookups, departments]) => setOptions({ ...lookups, departments })).catch((e) => { if (!c.signal.aborted) setError(getApiErrorMessage(e)) }); return () => c.abort() }, [])
  useEffect(() => { if (!search.trim()) { setEmployees([]); return undefined } const c = new AbortController(); const timer = setTimeout(() => pmsService.employees(search, c.signal).then((page) => setEmployees(page.content || [])).catch((e) => { if (!c.signal.aborted) setError(getApiErrorMessage(e)) }), 250); return () => { clearTimeout(timer); c.abort() } }, [search])
  useEffect(() => { if (status === 'COMPLETED') setValue('progressPercent', 100); if (status === 'NOT_STARTED') setValue('progressPercent', 0) }, [status, setValue])
  async function save(values) {
    setBusy(true); setError('')
    const payload = Object.fromEntries(Object.entries(values).map(([k, v]) => [k, v === '' ? null : v]))
    for (const key of ['employeeId', 'departmentId', 'categoryId', 'kraId', 'kpiId', 'alignmentGoalId', 'managerId']) if (payload[key] != null) payload[key] = Number(payload[key])
    for (const key of ['weightage', 'targetValue', 'progressPercent']) if (payload[key] != null) payload[key] = Number(payload[key])
    try { if (goal?.goalId) await pmsService.updateGoal(goal.goalId, payload); else await pmsService.createGoal(payload); notify({ type: 'success', message: goal ? 'Goal updated.' : 'Goal created.' }); onSaved(); onClose() }
    catch (e) { setError(getApiErrorMessage(e, 'Goal could not be saved.')) } finally { setBusy(false) }
  }
  const field = (label, key, control, rules = {}) => <label>{label}{control || <input {...register(key, rules)} />}{errors[key] && <small>{errors[key].message || 'Required'}</small>}</label>
  return <Modal title={goal ? 'Edit goal' : 'Create goal'} description="Define an outcome, owner and timeline." onClose={onClose} size="large">
    {error && <div className="pms-form-error">{error}</div>}
    <form className="pms-goal-form" onSubmit={handleSubmit(save)}>
      {field('Goal title', 'title', null, { required: 'A title is required.', maxLength: 200 })}
      <label className="field-span-two">Description<textarea rows="2" {...register('description')} /></label>
      <label>Find employee<input value={search} onChange={(e) => setSearch(e.target.value)} placeholder={goal?.employeeName || 'Search name or employee code'} /></label>
      {field('Goal owner', 'employeeId', <select {...register('employeeId', { required: 'Choose an employee.' })}><option value="">Select employee</option>{goal?.employeeId && <option value={goal.employeeId}>{goal.employeeName} · {goal.employeeCode}</option>}{employees.map((e) => <option key={e.employeeId} value={e.employeeId}>{e.displayName} · {e.employeeCode}</option>)}</select>, { required: 'Choose an employee.' })}
      {field('Department', 'departmentId', <select {...register('departmentId')}><option value="">Use employee department</option>{options.departments.map((d) => <option key={d.departmentId} value={d.departmentId}>{d.departmentName}</option>)}</select>)}
      {field('Category', 'categoryId', <select {...register('categoryId')}><option value="">Select category</option>{options.categories.map((o) => <option key={o.id} value={o.id}>{o.name}</option>)}</select>)}
      {field('Goal type', 'goalType', <select {...register('goalType')}><option>INDIVIDUAL</option><option>TEAM</option><option>DEPARTMENT</option><option>COMPANY</option></select>)}
      {field('KRA', 'kraId', <select {...register('kraId', { onChange: () => setValue('kpiId', '') })}><option value="">Select KRA</option>{options.kras.filter((o) => !categoryId || String(o.parentId) === String(categoryId)).map((o) => <option key={o.id} value={o.id}>{o.name}</option>)}</select>)}
      {field('KPI', 'kpiId', <select {...register('kpiId')}><option value="">Select KPI</option>{options.kpis.filter((o) => !kraId || String(o.parentId) === String(kraId)).map((o) => <option key={o.id} value={o.id}>{o.name}</option>)}</select>)}
      {field('Weightage (%)', 'weightage', null, { required: true, min: 0, max: 100 })}{field('Target value', 'targetValue', null, { required: true, min: 0.01 })}{field('Unit', 'unit', null, { required: true })}{field('Progress (%)', 'progressPercent', null, { min: 0, max: 100 })}
      {field('Priority', 'priority', <select {...register('priority')}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select>)}
      {field('Status', 'status', <select {...register('status')}><option>NOT_STARTED</option><option>IN_PROGRESS</option><option>BEHIND</option><option>COMPLETED</option></select>)}
      {field('Start date', 'startDate', <input type="date" {...register('startDate', { required: true })} />)}{field('Due date', 'dueDate', <input type="date" {...register('dueDate', { required: true })} />)}
      {field('Manager employee ID', 'managerId', <input type="number" min="1" {...register('managerId')} placeholder="Defaults to reporting manager" />)}{field('Aligned goal ID', 'alignmentGoalId', <input type="number" min="1" {...register('alignmentGoalId')} placeholder="Optional parent goal" />)}
      <div className="pms-form-actions"><button type="button" className="pms-button pms-button-secondary" onClick={onClose}>Cancel</button><button className="pms-button pms-button-primary" disabled={busy}>{busy ? 'Saving…' : goal ? 'Save changes' : 'Create goal'}</button></div>
    </form>
  </Modal>
}

function ProgressModal({ goal, onClose, onSaved, notify }) {
  const [progress, setProgress] = useState(Number(goal.progressPercent) || 0); const [comment, setComment] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function save() { setBusy(true); try { await pmsService.updateProgress(goal.goalId, { progressPercent: Number(progress), comment }); notify({ type: 'success', message: 'Goal progress updated.' }); onSaved(); onClose() } catch (e) { setError(getApiErrorMessage(e)) } finally { setBusy(false) } }
  return <Modal title="Update goal progress" description={goal.title} onClose={onClose}><div className="pms-progress-modal">{error && <div className="pms-form-error">{error}</div>}<label>Progress <strong>{progress}%</strong><input type="range" min="0" max="100" value={progress} onChange={(e) => setProgress(e.target.value)} /></label><label>Update note<textarea value={comment} onChange={(e) => setComment(e.target.value)} maxLength={300} rows="3" /></label><div className="pms-form-actions"><button className="pms-button pms-button-secondary" onClick={onClose}>Cancel</button><button className="pms-button pms-button-primary" onClick={save} disabled={busy}>Save progress</button></div></div></Modal>
}

function DetailModal({ goal, onClose }) {
  const [history, setHistory] = useState([])
  useEffect(() => { pmsService.history(goal.goalId).then(setHistory).catch(() => setHistory([])) }, [goal.goalId])
  return <Modal title={goal.title} description={`${goal.employeeName} · ${goal.department || 'No department'}`} onClose={onClose} size="large"><div className="pms-goal-detail"><div><GoalStatus status={goal.status} /><ProgressBar value={goal.progressPercent} /></div><p>{goal.description || 'No description provided.'}</p><p>{goal.category} · {goal.priority} · {goal.targetValue} {goal.unit}</p><p>{dateLabel(goal.startDate)} to {dateLabel(goal.dueDate)}</p><h3>History</h3>{history.map((item, i) => <div className="pms-history-row" key={`${item.changedAt}-${i}`}><b>{item.actionType}</b><span>{item.newValue || item.oldValue}</span><time>{dateLabel(item.changedAt)}</time></div>)}{!history.length && <small>No changes recorded.</small>}</div></Modal>
}

function GoalList({ mode, department, refresh, onEdit, onProgress, onView, notify, canManage, employeeOnly }) {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [priority, setPriority] = useState(''); const [page, setPage] = useState(0); const [size, setSize] = useState(10); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const scope = scopes[mode] || 'ALL'
  useEffect(() => { const c = new AbortController(); setLoading(true); setError(''); const params = { scope, page, size, sort: 'dueDate', direction: 'asc', ...(search ? { search } : {}), ...(status ? { status } : {}), ...(priority ? { priority } : {}), ...(department ? { department } : {}), ...(mode === 'department' ? { goalType: 'DEPARTMENT' } : {}) }; pmsService.listGoals(params, c.signal).then((result) => { if (!c.signal.aborted) { setData(result); setLoading(false) } }).catch((e) => { if (!c.signal.aborted) { setError(getApiErrorMessage(e, 'Goals could not be loaded.')); setLoading(false) } }); return () => c.abort() }, [scope, page, size, search, status, priority, department, mode, refresh])
  async function act(action, goal) { try { if (action === 'archive' && !window.confirm(`Archive “${goal.title}”?`)) return; if (action === 'delete' && !window.confirm(`Permanently delete “${goal.title}”?`)) return; if (action === 'archive') await pmsService.archiveGoal(goal.goalId); if (action === 'restore') await pmsService.restoreGoal(goal.goalId); if (action === 'delete') await pmsService.removeGoal(goal.goalId); notify({ type: 'success', message: `Goal ${action === 'delete' ? 'deleted' : `${action}d`}.` }); refresh() } catch (e) { notify({ type: 'error', message: getApiErrorMessage(e, 'Goal action failed.') }) } }
  return <Panel title={`${tabs.find((t) => t.id === mode)?.label || 'Goals'}${data ? ` · ${data.totalElements.toLocaleString()}` : ''}`} className="pms-goal-list-panel">
    <div className="pms-goal-filters"><label className="pms-search"><Search size={14} /><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(0) }} placeholder="Search goals or employees" /></label><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(0) }}><option value="">All statuses</option><option value="COMPLETED">Completed</option><option value="IN_PROGRESS">In progress</option><option value="BEHIND">Behind</option><option value="NOT_STARTED">Not started</option></select><select value={priority} onChange={(e) => { setPriority(e.target.value); setPage(0) }}><option value="">All priorities</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></div>
    {loading ? <div className="pms-list-loading" /> : error ? <div className="pms-form-error">{error}</div> : data?.content?.length ? <><div className="pms-table-scroll"><table className="pms-table pms-goal-table"><thead><tr><th>Goal</th><th>Employee</th><th>Department</th><th>Progress</th><th>Status</th><th>Priority</th><th>Due date</th><th>Actions</th></tr></thead><tbody>{data.content.map((goal) => <tr key={goal.goalId}><td><button className="pms-link-button" onClick={() => onView(goal)}>{goal.title}</button><small>{goal.category || goal.goalType}</small></td><td>{goal.employeeName}<small>{goal.employeeCode}</small></td><td>{goal.departmentGroup || goal.department || 'Others'}</td><td><ProgressBar value={goal.progressPercent} /></td><td><GoalStatus status={goal.status} />{goal.overdue && <small className="pms-overdue">Overdue</small>}</td><td>{goal.priority}</td><td>{dateLabel(goal.dueDate)}</td><td><div className="pms-row-actions"><button title="View" onClick={() => onView(goal)}><Eye size={14} /></button>{!goal.archived && canManage && <button title="Edit" onClick={() => onEdit(goal)}><Pencil size={14} /></button>}{!goal.archived && (canManage || employeeOnly) && <button title="Update progress" onClick={() => onProgress(goal)}><ArrowUp size={14} /></button>}{goal.archived ? canManage && <button title="Restore" onClick={() => act('restore', goal)}><RotateCcw size={14} /></button> : canManage && <button title="Archive" onClick={() => act('archive', goal)}><Archive size={14} /></button>}{canManage && <button title="Delete permanently" onClick={() => act('delete', goal)}><Trash2 size={14} /></button>}</div></td></tr>)}</tbody></table></div><Pagination page={data.page} totalPages={data.totalPages} totalElements={data.totalElements} size={data.size} onPageChange={setPage} onSizeChange={(v) => { setSize(v); setPage(0) }} noun="goals" /></> : <EmptyState title="No goals found" detail="Adjust the search or filters to see matching goals." />}
  </Panel>
}

function AlignmentNode({ node, depth = 0 }) {
  const [open, setOpen] = useState(depth < 1)
  return <div className="pms-tree-node" style={{ '--tree-depth': depth }}><button className="pms-tree-row" onClick={() => setOpen((v) => !v)}><i className={`pms-tree-marker tree-${node.goalType.toLowerCase()}`} /><span className="pms-tree-copy"><strong>{node.title}</strong><small>{node.goalType} · {node.owner} · {node.childCount} aligned</small></span><ProgressBar value={node.progressPercent} /><GoalStatus status={node.status} />{node.children.length > 0 && <b>{open ? '−' : '+'}</b>}</button>{open && node.children.map((child) => <AlignmentNode key={child.goalId} node={child} depth={depth + 1} />)}</div>
}

function AlignmentView({ revision }) {
  const [tree, setTree] = useState([]); const [error, setError] = useState('')
  useEffect(() => { const c = new AbortController(); pmsService.alignment(c.signal).then(setTree).catch((e) => { if (!c.signal.aborted) setError(getApiErrorMessage(e)) }); return () => c.abort() }, [revision])
  return <Panel title="Goal alignment"><p className="pms-alignment-intro">Company goals cascade through department, team and individual commitments.</p>{error ? <div className="pms-form-error">{error}</div> : tree.length ? tree.map((node) => <AlignmentNode key={node.goalId} node={node} />) : <EmptyState title="No aligned goals" />}</Panel>
}

function GoalCalendar({ revision, scope, department }) {
  const [month, setMonth] = useState(() => new Date()); const [events, setEvents] = useState([]); const [error, setError] = useState('')
  const year = month.getFullYear(); const m = month.getMonth(); const first = new Date(year, m, 1); const start = new Date(year, m, 1 - first.getDay()); const days = useMemo(() => Array.from({ length: 42 }, (_, i) => new Date(year, m, start.getDate() + i)), [year, m])
  useEffect(() => { const from = localDate(start); const to = localDate(new Date(start.getFullYear(), start.getMonth(), start.getDate() + 41)); pmsService.calendar({ from, to, scope, ...(department ? { department } : {}) }).then(setEvents).catch((e) => setError(getApiErrorMessage(e, 'Calendar could not be loaded.'))) }, [year, m, scope, department, revision])
  const keyed = new Map(); for (const e of events) keyed.set(e.date, [...(keyed.get(e.date) || []), e])
  return <Panel title="Goal calendar" action={<div className="pms-calendar-nav"><button aria-label="Previous month" onClick={() => setMonth(new Date(year, m - 1, 1))}><ChevronLeft size={16} /></button><strong>{month.toLocaleString('en', { month: 'long', year: 'numeric' })}</strong><button aria-label="Next month" onClick={() => setMonth(new Date(year, m + 1, 1))}><ChevronRight size={16} /></button></div>}>{error && <div className="pms-form-error">{error}</div>}<div className="pms-calendar-scroll"><div className="pms-calendar-grid">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((d) => <span className="pms-calendar-weekday" key={d}>{d}</span>)}{days.map((day) => { const key = localDate(day); const items = keyed.get(key) || []; return <div className={`pms-calendar-day ${day.getMonth() !== m ? 'is-outside' : ''} ${key === localDate(new Date()) ? 'is-today' : ''}`} key={key}><b>{day.getDate()}</b>{items.slice(0, 2).map((e) => <span className={`calendar-event event-${e.kind.toLowerCase()}`} title={e.title} key={`${e.goalId}-${e.kind}`}>{e.kind === 'DUE' ? 'Due' : 'Start'} · {e.title}</span>)}{items.length > 2 && <small>+{items.length - 2} more</small>}</div> })}</div></div></Panel>
}

export default function GoalManagementPage({ session, notify }) {
  const { tab: routeTab } = useParams(); const navigate = useNavigate(); const activeTab = tabs.some((t) => t.id === routeTab) ? routeTab : 'overview'
  const [range, setRange] = useState(defaultRange); const [department, setDepartment] = useState(''); const [overview, setOverview] = useState(null); const [trend, setTrend] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [revision, setRevision] = useState(0)
  const [creating, setCreating] = useState(false); const [editing, setEditing] = useState(null); const [updating, setUpdating] = useState(null); const [viewing, setViewing] = useState(null)
  const role = String(session?.role || session?.user?.role || '').toUpperCase(); const employeeOnly = role === 'EMPLOYEE'; const canManage = ['SUPER_ADMIN', 'HR_ADMIN', 'HR_MANAGER'].includes(role)
  const params = useMemo(() => ({ ...range, ...(department ? { department } : {}) }), [range, department]); const refresh = () => setRevision((v) => v + 1)
  useEffect(() => { const c = new AbortController(); setLoading(true); setError(''); Promise.all([pmsService.goalOverview(params, c.signal), pmsService.trend({ ...params, granularity: 'DAILY' }, c.signal)]).then(([o, t]) => { if (!c.signal.aborted) { setOverview(o); setTrend(t); setLoading(false) } }).catch((e) => { if (!c.signal.aborted) { setError(getApiErrorMessage(e, 'Goal data could not be loaded.')); setLoading(false) } }); return () => c.abort() }, [params, revision])
  async function exportReport() { try { await pmsService.exportGoals({ scope: activeTab === 'my' ? 'MY' : activeTab === 'team' ? 'TEAM' : 'ALL', ...(department ? { department } : {}) }) } catch (e) { notify({ type: 'error', message: getApiErrorMessage(e) }) } }
  const labels = [['total', 'Total Goals'], ['completed', 'Completed'], ['inProgress', 'In Progress'], ['behind', 'Behind'], ['notStarted', 'Not Started'], ['averageProgress', 'Average Progress', '%']]
  return <PageLayout eyebrow="PERFORMANCE MANAGEMENT" title="Goal Management" description="Set, align and track measurable goals across the organization." className="pms-page pms-goal-page">
    <div className="pms-goal-toolbar"><PageControls range={range} onRangeChange={setRange} department={department} onDepartmentChange={setDepartment} onExport={exportReport} exporting={false} tabs={tabs} activeTab={activeTab} onTabChange={(t) => navigate(`/performance/goal-management/${t}`)} />{canManage && <button className="pms-button pms-button-primary pms-create-button" onClick={() => setCreating(true)}><CirclePlus size={15} />Create New Goal</button>}</div>
    {loading ? <div className="pms-loading-grid"><div /><div /><div /><div /></div> : error ? <div className="pms-error"><strong>Goal data unavailable</strong><p>{error}</p><button className="pms-button pms-button-secondary" onClick={refresh}>Retry</button></div> : <>
      {activeTab === 'overview' && <><MetricCards values={overview?.kpis} labels={labels} invert={['behind', 'notStarted']} /><div className="pms-content-grid pms-grid-two"><TrendChart data={trend} mode="progress" /><DonutChart title="Goal status" rows={[{ name: 'Completed', value: overview?.summary?.completed || 0 }, { name: 'In Progress', value: overview?.summary?.inProgress || 0 }, { name: 'Behind', value: overview?.summary?.behind || 0 }, { name: 'Not Started', value: overview?.summary?.notStarted || 0 }]} nameKey="name" valueKey="value" colors={['#18866d', '#3975ca', '#d48a32', '#9da8b5']} centerValue={overview?.summary?.total || 0} centerLabel="Goals" /></div><div className="pms-content-grid pms-grid-two"><Panel title="My goals at a glance"><div className="pms-mini-goals">{overview?.myGoals?.map((g) => <div key={g.goalId}><span><strong>{g.title}</strong><small>{g.category || g.goalType} · due {dateLabel(g.dueDate)}</small></span><GoalStatus status={g.status} /><ProgressBar value={g.progressPercent} /></div>)}</div>{!overview?.myGoals?.length && <EmptyState title="No goals assigned" />}</Panel><DashboardDeadlines rows={overview?.deadlines} /></div><div className="pms-content-grid pms-grid-two"><DashboardTable rows={overview?.departmentGoals} /><Panel title="Goal alignment mix"><div className="pms-alignment-summary">{overview?.alignment?.map((r) => <div key={r.type}><span>{r.type}</span><strong>{r.count}</strong><small>{r.percent}%</small></div>)}</div></Panel></div><Panel title="Top goal categories"><div className="pms-category-list">{overview?.categories?.slice(0, 6).map((r) => <div key={r.category}><span>{r.category}</span><i><b style={{ width: `${r.percent}%` }} /></i><strong>{r.count}</strong></div>)}</div></Panel></>}
      {['my', 'team', 'department', 'archived'].includes(activeTab) && <GoalList mode={activeTab} department={department} refresh={revision} onEdit={setEditing} onProgress={setUpdating} onView={setViewing} notify={notify} canManage={canManage} employeeOnly={employeeOnly} />}
      {activeTab === 'alignment' && <AlignmentView revision={revision} />}{activeTab === 'calendar' && <GoalCalendar revision={revision} scope={activeTab === 'my' ? 'MY' : activeTab === 'team' ? 'TEAM' : 'ALL'} department={department} />}<PageFooter />
    </>}
    {(creating || editing) && <GoalModal goal={editing} onClose={() => { setCreating(false); setEditing(null) }} onSaved={refresh} notify={notify} />}{updating && <ProgressModal goal={updating} onClose={() => setUpdating(null)} onSaved={refresh} notify={notify} />}{viewing && <DetailModal goal={viewing} onClose={() => setViewing(null)} />}
  </PageLayout>
}
